name: basic_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Black.ttf
        weight: 200
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 300
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 400
      - asset: assets/fonts/Roboto-MediumItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 700
      - asset: assets/fonts/Roboto-ThinItalic.ttf
        weight: 700
        style: italic

  assets:
    - assets/images/biryani.jpg
    - assets/images/chapati.jpg
    - assets/images/indian.jpg
    
